MODEL:
  #PRETRAIN_CHOICE: 'imagenet'
  #PRETRAIN_PATH: 'pretrained_model/jx_vit_base_p16_224-80ecf9dd.pth'

  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'clipmix'
  NO_MARGIN: True
  DEVICE_ID: ('5')
  #TRANSFORMER_TYPE: 'vit_base_patch16_224_TransReID'
  STRIDE_SIZE: [12, 12]
  CLIPMIX_pretrain_choice: 'ViT-B/16'
  CLIPMIX_img_size: (128, 384)
  CLIPMIX_stride_size: 12




INPUT:
  SIZE_TRAIN: [128, 384]
  SIZE_TEST: [128, 384]
  PROB: 0.0 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: ('amurtiger')
  ROOT_DIR: ('data')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: "Adam"
  MAX_EPOCHS: 1500
  BASE_LR: 0.0008
  IMS_PER_BATCH: 32
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 50
  LOG_PERIOD: 10
  EVAL_PERIOD: 10
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2

TEST:
  EVAL: True
  IMS_PER_BATCH: 32
  RE_RANKING: False
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

OUTPUT_DIR: 'result'


